# Generated by Django 4.1.2 on 2022-10-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
