# Generated by Django 4.1.2 on 2022-10-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_borrow_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow_book',
            name='Book',
        ),
        migrations.AddField(
            model_name='borrow_book',
            name='Book',
            field=models.ManyToManyField(to='app.book'),
        ),
    ]
