# Generated by Django 4.1.2 on 2022-10-09 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_borrow_book_book_borrow_book_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book',
            name='Reader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.reader'),
        ),
    ]
